name: dart_merkletree
description: "A browsers compatible Dart implementation of a Merkle Tree data structure for efficient and secure data verification and storage."
version: 0.0.1
homepage: https://github.com/iden3/dart-merkletree

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  poseidon: ^0.0.1
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
